NisstonUniesp/projetoturmatarde

Joaoildefonso2023.txt
=> Solicitando contribuição Nisston

Elevir2023.txt
=> colaboração no git 

VictorErick2023.txt
=> Fazendo meu primeiro pull request para Nisston

Joaopedro.txt
=> fazendo meu primeiro pull

Abraão2023.txt
Solicitação do meu primeiro pull request
=> Solicitação do meu primeiro pull request

Nalbert2023.txt
=> Fazendo o meu primeiro pull

Gleysson2023.txt
=> Solicitando uma contribuição

Marcello2023.txt.txt
=> Sou o Marcello

Geovani2023.txt
=> Solicitando contribuicao Geovani.txt

Nisston2023.txt
Solicitando contribuicao Nisston
=> Solicitando contribuicao Nisston

lucas2023.txt.txt
Solicitando contribuição Lucas Neves
=> Solicitando contribuição Lucas Neves

henrique2023.txt
=> ola, sou henrique, solicitando contribuição

Eugenia2023.txt
Teste para primeiro pull request Eugenia
=> Teste para primeiro pull request Eugenia

Lucas Martins.txt
Solicitando contribuição | Lucas Martins
=> Solicitando contribuição | Lucas Martins

hugo2023.txt
=> carros tunados 2.0

Nalbert2023.txt, Nalbert2023.txt.bak
NÃO ERA SÓ COMIGO QUE VC FICAVA
=> TUDO BEM VAI SER MELHOR SÓ!!

Abraão2023.txt
=> Atualização ze da manga

Eugenia2023.txt, Eugenia2023.txt.bak
=> Alteração arquivo

Kevin Marques2023.txt
=> Modificação do arquivo Kevin Marques2023

Geovani2023.txt
=> Atualizacao doc txt

Micael2023.txt
=> aceita o request pf nisstonzada

lucas2023.txt.txt
=> atualização 2
